// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB_1seWaPOb9xvcrieNcqt4xnj7dk3cMQ',
    appId: '1:484466707561:android:85ad83031c11d472cce6f8',
    messagingSenderId: '484466707561',
    projectId: 'homeworkhelper-c86e8',
    databaseURL: 'https://homeworkhelper-c86e8-default-rtdb.firebaseio.com',
    storageBucket: 'homeworkhelper-c86e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArfSIFc3XJm0FAk5pH-uFtceL-tPWcwgY',
    appId: '1:484466707561:ios:fcdf655c52d83644cce6f8',
    messagingSenderId: '484466707561',
    projectId: 'homeworkhelper-c86e8',
    databaseURL: 'https://homeworkhelper-c86e8-default-rtdb.firebaseio.com',
    storageBucket: 'homeworkhelper-c86e8.appspot.com',
    iosClientId: '484466707561-t9iei8heka8aju2iml82d97vurate1sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeworkhelp',
  );
}
